In [20]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import matplotlib
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Carrega a versão mais recente especificando o arquivo correto
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "srisyra02/coffee-shop-sales-dataset",
  "Coffee Shop Sales.csv" # passando o dataset direto o kagglew ]
)

# Exibe as primeiras linhas do DataFrame
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1/1/23,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1/1/23,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1/1/23,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [21]:
df.shape

(149116, 11)

In [22]:
import pandas as pd #criando um dataframe simples pra trabalhar um pouco com cada ambiente

df = pd.DataFrame({
    'compra': [10, 20, 15, 30, 25,70],
    'venda':  [15, 25, 18, 40, 33,1]
})

df

   compra  venda
0      10     15
1      20     25
2      15     18
3      30     40
4      25     33
5      70      1

In [23]:
df['lucro'] = df['venda'] - df['compra'] #criando uma nova coluna
df

   compra  venda  lucro
0      10     15      5
1      20     25      5
2      15     18      3
3      30     40     10
4      25     33      8
5      70      1    -69

In [24]:
df['margem_%'] = (df['lucro'] / df['compra']) * 100  # margem percentual
df['status'] = df['lucro'].apply(lambda x: 'lucro' if x > 0 else 'prejuízo') #dando uma brincada com o apply
df

   compra  venda  lucro   margem_%    status
0      10     15      5  50.000000     lucro
1      20     25      5  25.000000     lucro
2      15     18      3  20.000000     lucro
3      30     40     10  33.333333     lucro
4      25     33      8  32.000000     lucro
5      70      1    -69 -98.571429  prejuízo